package com.example.mbg.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class MessageListExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table message_list
     *
     * @mbggenerated Tue Mar 22 15:50:19 CST 2022
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table message_list
     *
     * @mbggenerated Tue Mar 22 15:50:19 CST 2022
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table message_list
     *
     * @mbggenerated Tue Mar 22 15:50:19 CST 2022
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_list
     *
     * @mbggenerated Tue Mar 22 15:50:19 CST 2022
     */
    public MessageListExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_list
     *
     * @mbggenerated Tue Mar 22 15:50:19 CST 2022
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_list
     *
     * @mbggenerated Tue Mar 22 15:50:19 CST 2022
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_list
     *
     * @mbggenerated Tue Mar 22 15:50:19 CST 2022
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_list
     *
     * @mbggenerated Tue Mar 22 15:50:19 CST 2022
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_list
     *
     * @mbggenerated Tue Mar 22 15:50:19 CST 2022
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_list
     *
     * @mbggenerated Tue Mar 22 15:50:19 CST 2022
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_list
     *
     * @mbggenerated Tue Mar 22 15:50:19 CST 2022
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_list
     *
     * @mbggenerated Tue Mar 22 15:50:19 CST 2022
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_list
     *
     * @mbggenerated Tue Mar 22 15:50:19 CST 2022
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_list
     *
     * @mbggenerated Tue Mar 22 15:50:19 CST 2022
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table message_list
     *
     * @mbggenerated Tue Mar 22 15:50:19 CST 2022
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andMessageListIdIsNull() {
            addCriterion("message_list_id is null");
            return (Criteria) this;
        }

        public Criteria andMessageListIdIsNotNull() {
            addCriterion("message_list_id is not null");
            return (Criteria) this;
        }

        public Criteria andMessageListIdEqualTo(Integer value) {
            addCriterion("message_list_id =", value, "messageListId");
            return (Criteria) this;
        }

        public Criteria andMessageListIdNotEqualTo(Integer value) {
            addCriterion("message_list_id <>", value, "messageListId");
            return (Criteria) this;
        }

        public Criteria andMessageListIdGreaterThan(Integer value) {
            addCriterion("message_list_id >", value, "messageListId");
            return (Criteria) this;
        }

        public Criteria andMessageListIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("message_list_id >=", value, "messageListId");
            return (Criteria) this;
        }

        public Criteria andMessageListIdLessThan(Integer value) {
            addCriterion("message_list_id <", value, "messageListId");
            return (Criteria) this;
        }

        public Criteria andMessageListIdLessThanOrEqualTo(Integer value) {
            addCriterion("message_list_id <=", value, "messageListId");
            return (Criteria) this;
        }

        public Criteria andMessageListIdIn(List<Integer> values) {
            addCriterion("message_list_id in", values, "messageListId");
            return (Criteria) this;
        }

        public Criteria andMessageListIdNotIn(List<Integer> values) {
            addCriterion("message_list_id not in", values, "messageListId");
            return (Criteria) this;
        }

        public Criteria andMessageListIdBetween(Integer value1, Integer value2) {
            addCriterion("message_list_id between", value1, value2, "messageListId");
            return (Criteria) this;
        }

        public Criteria andMessageListIdNotBetween(Integer value1, Integer value2) {
            addCriterion("message_list_id not between", value1, value2, "messageListId");
            return (Criteria) this;
        }

        public Criteria andMessageHeadlineIsNull() {
            addCriterion("message_headline is null");
            return (Criteria) this;
        }

        public Criteria andMessageHeadlineIsNotNull() {
            addCriterion("message_headline is not null");
            return (Criteria) this;
        }

        public Criteria andMessageHeadlineEqualTo(String value) {
            addCriterion("message_headline =", value, "messageHeadline");
            return (Criteria) this;
        }

        public Criteria andMessageHeadlineNotEqualTo(String value) {
            addCriterion("message_headline <>", value, "messageHeadline");
            return (Criteria) this;
        }

        public Criteria andMessageHeadlineGreaterThan(String value) {
            addCriterion("message_headline >", value, "messageHeadline");
            return (Criteria) this;
        }

        public Criteria andMessageHeadlineGreaterThanOrEqualTo(String value) {
            addCriterion("message_headline >=", value, "messageHeadline");
            return (Criteria) this;
        }

        public Criteria andMessageHeadlineLessThan(String value) {
            addCriterion("message_headline <", value, "messageHeadline");
            return (Criteria) this;
        }

        public Criteria andMessageHeadlineLessThanOrEqualTo(String value) {
            addCriterion("message_headline <=", value, "messageHeadline");
            return (Criteria) this;
        }

        public Criteria andMessageHeadlineLike(String value) {
            addCriterion("message_headline like", value, "messageHeadline");
            return (Criteria) this;
        }

        public Criteria andMessageHeadlineNotLike(String value) {
            addCriterion("message_headline not like", value, "messageHeadline");
            return (Criteria) this;
        }

        public Criteria andMessageHeadlineIn(List<String> values) {
            addCriterion("message_headline in", values, "messageHeadline");
            return (Criteria) this;
        }

        public Criteria andMessageHeadlineNotIn(List<String> values) {
            addCriterion("message_headline not in", values, "messageHeadline");
            return (Criteria) this;
        }

        public Criteria andMessageHeadlineBetween(String value1, String value2) {
            addCriterion("message_headline between", value1, value2, "messageHeadline");
            return (Criteria) this;
        }

        public Criteria andMessageHeadlineNotBetween(String value1, String value2) {
            addCriterion("message_headline not between", value1, value2, "messageHeadline");
            return (Criteria) this;
        }

        public Criteria andMessageContentIsNull() {
            addCriterion("message_content is null");
            return (Criteria) this;
        }

        public Criteria andMessageContentIsNotNull() {
            addCriterion("message_content is not null");
            return (Criteria) this;
        }

        public Criteria andMessageContentEqualTo(String value) {
            addCriterion("message_content =", value, "messageContent");
            return (Criteria) this;
        }

        public Criteria andMessageContentNotEqualTo(String value) {
            addCriterion("message_content <>", value, "messageContent");
            return (Criteria) this;
        }

        public Criteria andMessageContentGreaterThan(String value) {
            addCriterion("message_content >", value, "messageContent");
            return (Criteria) this;
        }

        public Criteria andMessageContentGreaterThanOrEqualTo(String value) {
            addCriterion("message_content >=", value, "messageContent");
            return (Criteria) this;
        }

        public Criteria andMessageContentLessThan(String value) {
            addCriterion("message_content <", value, "messageContent");
            return (Criteria) this;
        }

        public Criteria andMessageContentLessThanOrEqualTo(String value) {
            addCriterion("message_content <=", value, "messageContent");
            return (Criteria) this;
        }

        public Criteria andMessageContentLike(String value) {
            addCriterion("message_content like", value, "messageContent");
            return (Criteria) this;
        }

        public Criteria andMessageContentNotLike(String value) {
            addCriterion("message_content not like", value, "messageContent");
            return (Criteria) this;
        }

        public Criteria andMessageContentIn(List<String> values) {
            addCriterion("message_content in", values, "messageContent");
            return (Criteria) this;
        }

        public Criteria andMessageContentNotIn(List<String> values) {
            addCriterion("message_content not in", values, "messageContent");
            return (Criteria) this;
        }

        public Criteria andMessageContentBetween(String value1, String value2) {
            addCriterion("message_content between", value1, value2, "messageContent");
            return (Criteria) this;
        }

        public Criteria andMessageContentNotBetween(String value1, String value2) {
            addCriterion("message_content not between", value1, value2, "messageContent");
            return (Criteria) this;
        }

        public Criteria andMessageStIsNull() {
            addCriterion("message_st is null");
            return (Criteria) this;
        }

        public Criteria andMessageStIsNotNull() {
            addCriterion("message_st is not null");
            return (Criteria) this;
        }

        public Criteria andMessageStEqualTo(Date value) {
            addCriterion("message_st =", value, "messageSt");
            return (Criteria) this;
        }

        public Criteria andMessageStNotEqualTo(Date value) {
            addCriterion("message_st <>", value, "messageSt");
            return (Criteria) this;
        }

        public Criteria andMessageStGreaterThan(Date value) {
            addCriterion("message_st >", value, "messageSt");
            return (Criteria) this;
        }

        public Criteria andMessageStGreaterThanOrEqualTo(Date value) {
            addCriterion("message_st >=", value, "messageSt");
            return (Criteria) this;
        }

        public Criteria andMessageStLessThan(Date value) {
            addCriterion("message_st <", value, "messageSt");
            return (Criteria) this;
        }

        public Criteria andMessageStLessThanOrEqualTo(Date value) {
            addCriterion("message_st <=", value, "messageSt");
            return (Criteria) this;
        }

        public Criteria andMessageStIn(List<Date> values) {
            addCriterion("message_st in", values, "messageSt");
            return (Criteria) this;
        }

        public Criteria andMessageStNotIn(List<Date> values) {
            addCriterion("message_st not in", values, "messageSt");
            return (Criteria) this;
        }

        public Criteria andMessageStBetween(Date value1, Date value2) {
            addCriterion("message_st between", value1, value2, "messageSt");
            return (Criteria) this;
        }

        public Criteria andMessageStNotBetween(Date value1, Date value2) {
            addCriterion("message_st not between", value1, value2, "messageSt");
            return (Criteria) this;
        }

        public Criteria andMessagePatternIsNull() {
            addCriterion("message_pattern is null");
            return (Criteria) this;
        }

        public Criteria andMessagePatternIsNotNull() {
            addCriterion("message_pattern is not null");
            return (Criteria) this;
        }

        public Criteria andMessagePatternEqualTo(String value) {
            addCriterion("message_pattern =", value, "messagePattern");
            return (Criteria) this;
        }

        public Criteria andMessagePatternNotEqualTo(String value) {
            addCriterion("message_pattern <>", value, "messagePattern");
            return (Criteria) this;
        }

        public Criteria andMessagePatternGreaterThan(String value) {
            addCriterion("message_pattern >", value, "messagePattern");
            return (Criteria) this;
        }

        public Criteria andMessagePatternGreaterThanOrEqualTo(String value) {
            addCriterion("message_pattern >=", value, "messagePattern");
            return (Criteria) this;
        }

        public Criteria andMessagePatternLessThan(String value) {
            addCriterion("message_pattern <", value, "messagePattern");
            return (Criteria) this;
        }

        public Criteria andMessagePatternLessThanOrEqualTo(String value) {
            addCriterion("message_pattern <=", value, "messagePattern");
            return (Criteria) this;
        }

        public Criteria andMessagePatternLike(String value) {
            addCriterion("message_pattern like", value, "messagePattern");
            return (Criteria) this;
        }

        public Criteria andMessagePatternNotLike(String value) {
            addCriterion("message_pattern not like", value, "messagePattern");
            return (Criteria) this;
        }

        public Criteria andMessagePatternIn(List<String> values) {
            addCriterion("message_pattern in", values, "messagePattern");
            return (Criteria) this;
        }

        public Criteria andMessagePatternNotIn(List<String> values) {
            addCriterion("message_pattern not in", values, "messagePattern");
            return (Criteria) this;
        }

        public Criteria andMessagePatternBetween(String value1, String value2) {
            addCriterion("message_pattern between", value1, value2, "messagePattern");
            return (Criteria) this;
        }

        public Criteria andMessagePatternNotBetween(String value1, String value2) {
            addCriterion("message_pattern not between", value1, value2, "messagePattern");
            return (Criteria) this;
        }

        public Criteria andMessageIconIsNull() {
            addCriterion("message_icon is null");
            return (Criteria) this;
        }

        public Criteria andMessageIconIsNotNull() {
            addCriterion("message_icon is not null");
            return (Criteria) this;
        }

        public Criteria andMessageIconEqualTo(String value) {
            addCriterion("message_icon =", value, "messageIcon");
            return (Criteria) this;
        }

        public Criteria andMessageIconNotEqualTo(String value) {
            addCriterion("message_icon <>", value, "messageIcon");
            return (Criteria) this;
        }

        public Criteria andMessageIconGreaterThan(String value) {
            addCriterion("message_icon >", value, "messageIcon");
            return (Criteria) this;
        }

        public Criteria andMessageIconGreaterThanOrEqualTo(String value) {
            addCriterion("message_icon >=", value, "messageIcon");
            return (Criteria) this;
        }

        public Criteria andMessageIconLessThan(String value) {
            addCriterion("message_icon <", value, "messageIcon");
            return (Criteria) this;
        }

        public Criteria andMessageIconLessThanOrEqualTo(String value) {
            addCriterion("message_icon <=", value, "messageIcon");
            return (Criteria) this;
        }

        public Criteria andMessageIconLike(String value) {
            addCriterion("message_icon like", value, "messageIcon");
            return (Criteria) this;
        }

        public Criteria andMessageIconNotLike(String value) {
            addCriterion("message_icon not like", value, "messageIcon");
            return (Criteria) this;
        }

        public Criteria andMessageIconIn(List<String> values) {
            addCriterion("message_icon in", values, "messageIcon");
            return (Criteria) this;
        }

        public Criteria andMessageIconNotIn(List<String> values) {
            addCriterion("message_icon not in", values, "messageIcon");
            return (Criteria) this;
        }

        public Criteria andMessageIconBetween(String value1, String value2) {
            addCriterion("message_icon between", value1, value2, "messageIcon");
            return (Criteria) this;
        }

        public Criteria andMessageIconNotBetween(String value1, String value2) {
            addCriterion("message_icon not between", value1, value2, "messageIcon");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table message_list
     *
     * @mbggenerated do_not_delete_during_merge Tue Mar 22 15:50:19 CST 2022
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table message_list
     *
     * @mbggenerated Tue Mar 22 15:50:19 CST 2022
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}