package com.example.mbg.model;

import java.util.ArrayList;
import java.util.List;

public class RegisterExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table register
     *
     * @mbggenerated Sat Mar 26 18:14:29 CST 2022
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table register
     *
     * @mbggenerated Sat Mar 26 18:14:29 CST 2022
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table register
     *
     * @mbggenerated Sat Mar 26 18:14:29 CST 2022
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table register
     *
     * @mbggenerated Sat Mar 26 18:14:29 CST 2022
     */
    public RegisterExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table register
     *
     * @mbggenerated Sat Mar 26 18:14:29 CST 2022
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table register
     *
     * @mbggenerated Sat Mar 26 18:14:29 CST 2022
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table register
     *
     * @mbggenerated Sat Mar 26 18:14:29 CST 2022
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table register
     *
     * @mbggenerated Sat Mar 26 18:14:29 CST 2022
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table register
     *
     * @mbggenerated Sat Mar 26 18:14:29 CST 2022
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table register
     *
     * @mbggenerated Sat Mar 26 18:14:29 CST 2022
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table register
     *
     * @mbggenerated Sat Mar 26 18:14:29 CST 2022
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table register
     *
     * @mbggenerated Sat Mar 26 18:14:29 CST 2022
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table register
     *
     * @mbggenerated Sat Mar 26 18:14:29 CST 2022
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table register
     *
     * @mbggenerated Sat Mar 26 18:14:29 CST 2022
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table register
     *
     * @mbggenerated Sat Mar 26 18:14:29 CST 2022
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andRegisterIdIsNull() {
            addCriterion("register_id is null");
            return (Criteria) this;
        }

        public Criteria andRegisterIdIsNotNull() {
            addCriterion("register_id is not null");
            return (Criteria) this;
        }

        public Criteria andRegisterIdEqualTo(Integer value) {
            addCriterion("register_id =", value, "registerId");
            return (Criteria) this;
        }

        public Criteria andRegisterIdNotEqualTo(Integer value) {
            addCriterion("register_id <>", value, "registerId");
            return (Criteria) this;
        }

        public Criteria andRegisterIdGreaterThan(Integer value) {
            addCriterion("register_id >", value, "registerId");
            return (Criteria) this;
        }

        public Criteria andRegisterIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("register_id >=", value, "registerId");
            return (Criteria) this;
        }

        public Criteria andRegisterIdLessThan(Integer value) {
            addCriterion("register_id <", value, "registerId");
            return (Criteria) this;
        }

        public Criteria andRegisterIdLessThanOrEqualTo(Integer value) {
            addCriterion("register_id <=", value, "registerId");
            return (Criteria) this;
        }

        public Criteria andRegisterIdIn(List<Integer> values) {
            addCriterion("register_id in", values, "registerId");
            return (Criteria) this;
        }

        public Criteria andRegisterIdNotIn(List<Integer> values) {
            addCriterion("register_id not in", values, "registerId");
            return (Criteria) this;
        }

        public Criteria andRegisterIdBetween(Integer value1, Integer value2) {
            addCriterion("register_id between", value1, value2, "registerId");
            return (Criteria) this;
        }

        public Criteria andRegisterIdNotBetween(Integer value1, Integer value2) {
            addCriterion("register_id not between", value1, value2, "registerId");
            return (Criteria) this;
        }

        public Criteria andRegisterPhotoIsNull() {
            addCriterion("register_photo is null");
            return (Criteria) this;
        }

        public Criteria andRegisterPhotoIsNotNull() {
            addCriterion("register_photo is not null");
            return (Criteria) this;
        }

        public Criteria andRegisterPhotoEqualTo(String value) {
            addCriterion("register_photo =", value, "registerPhoto");
            return (Criteria) this;
        }

        public Criteria andRegisterPhotoNotEqualTo(String value) {
            addCriterion("register_photo <>", value, "registerPhoto");
            return (Criteria) this;
        }

        public Criteria andRegisterPhotoGreaterThan(String value) {
            addCriterion("register_photo >", value, "registerPhoto");
            return (Criteria) this;
        }

        public Criteria andRegisterPhotoGreaterThanOrEqualTo(String value) {
            addCriterion("register_photo >=", value, "registerPhoto");
            return (Criteria) this;
        }

        public Criteria andRegisterPhotoLessThan(String value) {
            addCriterion("register_photo <", value, "registerPhoto");
            return (Criteria) this;
        }

        public Criteria andRegisterPhotoLessThanOrEqualTo(String value) {
            addCriterion("register_photo <=", value, "registerPhoto");
            return (Criteria) this;
        }

        public Criteria andRegisterPhotoLike(String value) {
            addCriterion("register_photo like", value, "registerPhoto");
            return (Criteria) this;
        }

        public Criteria andRegisterPhotoNotLike(String value) {
            addCriterion("register_photo not like", value, "registerPhoto");
            return (Criteria) this;
        }

        public Criteria andRegisterPhotoIn(List<String> values) {
            addCriterion("register_photo in", values, "registerPhoto");
            return (Criteria) this;
        }

        public Criteria andRegisterPhotoNotIn(List<String> values) {
            addCriterion("register_photo not in", values, "registerPhoto");
            return (Criteria) this;
        }

        public Criteria andRegisterPhotoBetween(String value1, String value2) {
            addCriterion("register_photo between", value1, value2, "registerPhoto");
            return (Criteria) this;
        }

        public Criteria andRegisterPhotoNotBetween(String value1, String value2) {
            addCriterion("register_photo not between", value1, value2, "registerPhoto");
            return (Criteria) this;
        }

        public Criteria andRegisterNicknameIsNull() {
            addCriterion("register_nickname is null");
            return (Criteria) this;
        }

        public Criteria andRegisterNicknameIsNotNull() {
            addCriterion("register_nickname is not null");
            return (Criteria) this;
        }

        public Criteria andRegisterNicknameEqualTo(String value) {
            addCriterion("register_nickname =", value, "registerNickname");
            return (Criteria) this;
        }

        public Criteria andRegisterNicknameNotEqualTo(String value) {
            addCriterion("register_nickname <>", value, "registerNickname");
            return (Criteria) this;
        }

        public Criteria andRegisterNicknameGreaterThan(String value) {
            addCriterion("register_nickname >", value, "registerNickname");
            return (Criteria) this;
        }

        public Criteria andRegisterNicknameGreaterThanOrEqualTo(String value) {
            addCriterion("register_nickname >=", value, "registerNickname");
            return (Criteria) this;
        }

        public Criteria andRegisterNicknameLessThan(String value) {
            addCriterion("register_nickname <", value, "registerNickname");
            return (Criteria) this;
        }

        public Criteria andRegisterNicknameLessThanOrEqualTo(String value) {
            addCriterion("register_nickname <=", value, "registerNickname");
            return (Criteria) this;
        }

        public Criteria andRegisterNicknameLike(String value) {
            addCriterion("register_nickname like", value, "registerNickname");
            return (Criteria) this;
        }

        public Criteria andRegisterNicknameNotLike(String value) {
            addCriterion("register_nickname not like", value, "registerNickname");
            return (Criteria) this;
        }

        public Criteria andRegisterNicknameIn(List<String> values) {
            addCriterion("register_nickname in", values, "registerNickname");
            return (Criteria) this;
        }

        public Criteria andRegisterNicknameNotIn(List<String> values) {
            addCriterion("register_nickname not in", values, "registerNickname");
            return (Criteria) this;
        }

        public Criteria andRegisterNicknameBetween(String value1, String value2) {
            addCriterion("register_nickname between", value1, value2, "registerNickname");
            return (Criteria) this;
        }

        public Criteria andRegisterNicknameNotBetween(String value1, String value2) {
            addCriterion("register_nickname not between", value1, value2, "registerNickname");
            return (Criteria) this;
        }

        public Criteria andRegisterStateIsNull() {
            addCriterion("register_state is null");
            return (Criteria) this;
        }

        public Criteria andRegisterStateIsNotNull() {
            addCriterion("register_state is not null");
            return (Criteria) this;
        }

        public Criteria andRegisterStateEqualTo(String value) {
            addCriterion("register_state =", value, "registerState");
            return (Criteria) this;
        }

        public Criteria andRegisterStateNotEqualTo(String value) {
            addCriterion("register_state <>", value, "registerState");
            return (Criteria) this;
        }

        public Criteria andRegisterStateGreaterThan(String value) {
            addCriterion("register_state >", value, "registerState");
            return (Criteria) this;
        }

        public Criteria andRegisterStateGreaterThanOrEqualTo(String value) {
            addCriterion("register_state >=", value, "registerState");
            return (Criteria) this;
        }

        public Criteria andRegisterStateLessThan(String value) {
            addCriterion("register_state <", value, "registerState");
            return (Criteria) this;
        }

        public Criteria andRegisterStateLessThanOrEqualTo(String value) {
            addCriterion("register_state <=", value, "registerState");
            return (Criteria) this;
        }

        public Criteria andRegisterStateLike(String value) {
            addCriterion("register_state like", value, "registerState");
            return (Criteria) this;
        }

        public Criteria andRegisterStateNotLike(String value) {
            addCriterion("register_state not like", value, "registerState");
            return (Criteria) this;
        }

        public Criteria andRegisterStateIn(List<String> values) {
            addCriterion("register_state in", values, "registerState");
            return (Criteria) this;
        }

        public Criteria andRegisterStateNotIn(List<String> values) {
            addCriterion("register_state not in", values, "registerState");
            return (Criteria) this;
        }

        public Criteria andRegisterStateBetween(String value1, String value2) {
            addCriterion("register_state between", value1, value2, "registerState");
            return (Criteria) this;
        }

        public Criteria andRegisterStateNotBetween(String value1, String value2) {
            addCriterion("register_state not between", value1, value2, "registerState");
            return (Criteria) this;
        }

        public Criteria andRegisterCellIsNull() {
            addCriterion("register_cell is null");
            return (Criteria) this;
        }

        public Criteria andRegisterCellIsNotNull() {
            addCriterion("register_cell is not null");
            return (Criteria) this;
        }

        public Criteria andRegisterCellEqualTo(Integer value) {
            addCriterion("register_cell =", value, "registerCell");
            return (Criteria) this;
        }

        public Criteria andRegisterCellNotEqualTo(Integer value) {
            addCriterion("register_cell <>", value, "registerCell");
            return (Criteria) this;
        }

        public Criteria andRegisterCellGreaterThan(Integer value) {
            addCriterion("register_cell >", value, "registerCell");
            return (Criteria) this;
        }

        public Criteria andRegisterCellGreaterThanOrEqualTo(Integer value) {
            addCriterion("register_cell >=", value, "registerCell");
            return (Criteria) this;
        }

        public Criteria andRegisterCellLessThan(Integer value) {
            addCriterion("register_cell <", value, "registerCell");
            return (Criteria) this;
        }

        public Criteria andRegisterCellLessThanOrEqualTo(Integer value) {
            addCriterion("register_cell <=", value, "registerCell");
            return (Criteria) this;
        }

        public Criteria andRegisterCellIn(List<Integer> values) {
            addCriterion("register_cell in", values, "registerCell");
            return (Criteria) this;
        }

        public Criteria andRegisterCellNotIn(List<Integer> values) {
            addCriterion("register_cell not in", values, "registerCell");
            return (Criteria) this;
        }

        public Criteria andRegisterCellBetween(Integer value1, Integer value2) {
            addCriterion("register_cell between", value1, value2, "registerCell");
            return (Criteria) this;
        }

        public Criteria andRegisterCellNotBetween(Integer value1, Integer value2) {
            addCriterion("register_cell not between", value1, value2, "registerCell");
            return (Criteria) this;
        }

        public Criteria andRegisterPassIsNull() {
            addCriterion("register_pass is null");
            return (Criteria) this;
        }

        public Criteria andRegisterPassIsNotNull() {
            addCriterion("register_pass is not null");
            return (Criteria) this;
        }

        public Criteria andRegisterPassEqualTo(String value) {
            addCriterion("register_pass =", value, "registerPass");
            return (Criteria) this;
        }

        public Criteria andRegisterPassNotEqualTo(String value) {
            addCriterion("register_pass <>", value, "registerPass");
            return (Criteria) this;
        }

        public Criteria andRegisterPassGreaterThan(String value) {
            addCriterion("register_pass >", value, "registerPass");
            return (Criteria) this;
        }

        public Criteria andRegisterPassGreaterThanOrEqualTo(String value) {
            addCriterion("register_pass >=", value, "registerPass");
            return (Criteria) this;
        }

        public Criteria andRegisterPassLessThan(String value) {
            addCriterion("register_pass <", value, "registerPass");
            return (Criteria) this;
        }

        public Criteria andRegisterPassLessThanOrEqualTo(String value) {
            addCriterion("register_pass <=", value, "registerPass");
            return (Criteria) this;
        }

        public Criteria andRegisterPassLike(String value) {
            addCriterion("register_pass like", value, "registerPass");
            return (Criteria) this;
        }

        public Criteria andRegisterPassNotLike(String value) {
            addCriterion("register_pass not like", value, "registerPass");
            return (Criteria) this;
        }

        public Criteria andRegisterPassIn(List<String> values) {
            addCriterion("register_pass in", values, "registerPass");
            return (Criteria) this;
        }

        public Criteria andRegisterPassNotIn(List<String> values) {
            addCriterion("register_pass not in", values, "registerPass");
            return (Criteria) this;
        }

        public Criteria andRegisterPassBetween(String value1, String value2) {
            addCriterion("register_pass between", value1, value2, "registerPass");
            return (Criteria) this;
        }

        public Criteria andRegisterPassNotBetween(String value1, String value2) {
            addCriterion("register_pass not between", value1, value2, "registerPass");
            return (Criteria) this;
        }

        public Criteria andVerifIsNull() {
            addCriterion("verif is null");
            return (Criteria) this;
        }

        public Criteria andVerifIsNotNull() {
            addCriterion("verif is not null");
            return (Criteria) this;
        }

        public Criteria andVerifEqualTo(Integer value) {
            addCriterion("verif =", value, "verif");
            return (Criteria) this;
        }

        public Criteria andVerifNotEqualTo(Integer value) {
            addCriterion("verif <>", value, "verif");
            return (Criteria) this;
        }

        public Criteria andVerifGreaterThan(Integer value) {
            addCriterion("verif >", value, "verif");
            return (Criteria) this;
        }

        public Criteria andVerifGreaterThanOrEqualTo(Integer value) {
            addCriterion("verif >=", value, "verif");
            return (Criteria) this;
        }

        public Criteria andVerifLessThan(Integer value) {
            addCriterion("verif <", value, "verif");
            return (Criteria) this;
        }

        public Criteria andVerifLessThanOrEqualTo(Integer value) {
            addCriterion("verif <=", value, "verif");
            return (Criteria) this;
        }

        public Criteria andVerifIn(List<Integer> values) {
            addCriterion("verif in", values, "verif");
            return (Criteria) this;
        }

        public Criteria andVerifNotIn(List<Integer> values) {
            addCriterion("verif not in", values, "verif");
            return (Criteria) this;
        }

        public Criteria andVerifBetween(Integer value1, Integer value2) {
            addCriterion("verif between", value1, value2, "verif");
            return (Criteria) this;
        }

        public Criteria andVerifNotBetween(Integer value1, Integer value2) {
            addCriterion("verif not between", value1, value2, "verif");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table register
     *
     * @mbggenerated do_not_delete_during_merge Sat Mar 26 18:14:29 CST 2022
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table register
     *
     * @mbggenerated Sat Mar 26 18:14:29 CST 2022
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}