package com.example.mbg.model;

import com.baomidou.mybatisplus.annotation.TableName;
import org.springframework.stereotype.Component;

import java.io.Serializable;

@Component
@TableName("/register")
public class Register implements Serializable {

    private Integer registerId;
    private String registerPhoto;
    private String registerNickname;
    private String registerState;
    private Integer registerCell;
    private String registerPass;
    private Integer verif;

    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column register.register_id
     *
     * @return the value of register.register_id
     *
     * @mbggenerated Sat Mar 26 18:14:29 CST 2022
     */
    public Integer getRegisterId() {
        return registerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column register.register_id
     *
     * @param registerId the value for register.register_id
     *
     * @mbggenerated Sat Mar 26 18:14:29 CST 2022
     */
    public void setRegisterId(Integer registerId) {
        this.registerId = registerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column register.register_photo
     *
     * @return the value of register.register_photo
     *
     * @mbggenerated Sat Mar 26 18:14:29 CST 2022
     */
    public String getRegisterPhoto() {
        return registerPhoto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column register.register_photo
     *
     * @param registerPhoto the value for register.register_photo
     *
     * @mbggenerated Sat Mar 26 18:14:29 CST 2022
     */
    public void setRegisterPhoto(String registerPhoto) {
        this.registerPhoto = registerPhoto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column register.register_nickname
     *
     * @return the value of register.register_nickname
     *
     * @mbggenerated Sat Mar 26 18:14:29 CST 2022
     */
    public String getRegisterNickname() {
        return registerNickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column register.register_nickname
     *
     * @param registerNickname the value for register.register_nickname
     *
     * @mbggenerated Sat Mar 26 18:14:29 CST 2022
     */
    public void setRegisterNickname(String registerNickname) {
        this.registerNickname = registerNickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column register.register_state
     *
     * @return the value of register.register_state
     *
     * @mbggenerated Sat Mar 26 18:14:29 CST 2022
     */
    public String getRegisterState() {
        return registerState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column register.register_state
     *
     * @param registerState the value for register.register_state
     *
     * @mbggenerated Sat Mar 26 18:14:29 CST 2022
     */
    public void setRegisterState(String registerState) {
        this.registerState = registerState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column register.register_cell
     *
     * @return the value of register.register_cell
     *
     * @mbggenerated Sat Mar 26 18:14:29 CST 2022
     */
    public Integer getRegisterCell() {
        return registerCell;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column register.register_cell
     *
     * @param registerCell the value for register.register_cell
     *
     * @mbggenerated Sat Mar 26 18:14:29 CST 2022
     */
    public void setRegisterCell(Integer registerCell) {
        this.registerCell = registerCell;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column register.register_pass
     *
     * @return the value of register.register_pass
     *
     * @mbggenerated Sat Mar 26 18:14:29 CST 2022
     */
    public String getRegisterPass() {
        return registerPass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column register.register_pass
     *
     * @param registerPass the value for register.register_pass
     *
     * @mbggenerated Sat Mar 26 18:14:29 CST 2022
     */
    public void setRegisterPass(String registerPass) {
        this.registerPass = registerPass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column register.verif
     *
     * @return the value of register.verif
     *
     * @mbggenerated Sat Mar 26 18:14:29 CST 2022
     */
    public Integer getVerif() {
        return verif;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column register.verif
     *
     * @param verif the value for register.verif
     *
     * @mbggenerated Sat Mar 26 18:14:29 CST 2022
     */
    public void setVerif(Integer verif) {
        this.verif = verif;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table register
     *
     * @mbggenerated Sat Mar 26 18:14:29 CST 2022
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", registerId=").append(registerId);
        sb.append(", registerPhoto=").append(registerPhoto);
        sb.append(", registerNickname=").append(registerNickname);
        sb.append(", registerState=").append(registerState);
        sb.append(", registerCell=").append(registerCell);
        sb.append(", registerPass=").append(registerPass);
        sb.append(", verif=").append(verif);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}