package com.example.mbg.mapper;

import com.example.mbg.model.MessageList;
import com.example.mbg.model.MessageListExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MessageListMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_list
     *
     * @mbggenerated Tue Mar 22 15:50:19 CST 2022
     */
    int countByExample(MessageListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_list
     *
     * @mbggenerated Tue Mar 22 15:50:19 CST 2022
     */
    int deleteByExample(MessageListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_list
     *
     * @mbggenerated Tue Mar 22 15:50:19 CST 2022
     */
    int deleteByPrimaryKey(Integer messageListId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_list
     *
     * @mbggenerated Tue Mar 22 15:50:19 CST 2022
     */
    int insert(MessageList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_list
     *
     * @mbggenerated Tue Mar 22 15:50:19 CST 2022
     */
    int insertSelective(MessageList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_list
     *
     * @mbggenerated Tue Mar 22 15:50:19 CST 2022
     */
    List<MessageList> selectByExample(MessageListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_list
     *
     * @mbggenerated Tue Mar 22 15:50:19 CST 2022
     */
    MessageList selectByPrimaryKey(Integer messageListId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_list
     *
     * @mbggenerated Tue Mar 22 15:50:19 CST 2022
     */
    int updateByExampleSelective(@Param("record") MessageList record, @Param("example") MessageListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_list
     *
     * @mbggenerated Tue Mar 22 15:50:19 CST 2022
     */
    int updateByExample(@Param("record") MessageList record, @Param("example") MessageListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_list
     *
     * @mbggenerated Tue Mar 22 15:50:19 CST 2022
     */
    int updateByPrimaryKeySelective(MessageList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_list
     *
     * @mbggenerated Tue Mar 22 15:50:19 CST 2022
     */
    int updateByPrimaryKey(MessageList record);
}