package com.example.mbg.mapper;

import com.example.mbg.model.Register;
import com.example.mbg.model.RegisterExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RegisterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table register
     *
     * @mbggenerated Sat Mar 26 18:14:29 CST 2022
     */
    int countByExample(RegisterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table register
     *
     * @mbggenerated Sat Mar 26 18:14:29 CST 2022
     */
    int deleteByExample(RegisterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table register
     *
     * @mbggenerated Sat Mar 26 18:14:29 CST 2022
     */
    int deleteByPrimaryKey(Integer registerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table register
     *
     * @mbggenerated Sat Mar 26 18:14:29 CST 2022
     */
    int insert(Register record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table register
     *
     * @mbggenerated Sat Mar 26 18:14:29 CST 2022
     */
    int insertSelective(Register record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table register
     *
     * @mbggenerated Sat Mar 26 18:14:29 CST 2022
     */
    List<Register> selectByExample(RegisterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table register
     *
     * @mbggenerated Sat Mar 26 18:14:29 CST 2022
     */
    Register selectByPrimaryKey(Integer registerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table register
     *
     * @mbggenerated Sat Mar 26 18:14:29 CST 2022
     */
    int updateByExampleSelective(@Param("record") Register record, @Param("example") RegisterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table register
     *
     * @mbggenerated Sat Mar 26 18:14:29 CST 2022
     */
    int updateByExample(@Param("record") Register record, @Param("example") RegisterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table register
     *
     * @mbggenerated Sat Mar 26 18:14:29 CST 2022
     */
    int updateByPrimaryKeySelective(Register record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table register
     *
     * @mbggenerated Sat Mar 26 18:14:29 CST 2022
     */
    int updateByPrimaryKey(Register record);

    /**
     * 登录
     * @param registerCell
     * @param registerPass
     * @return
     */
    Register selectTelPass(Integer registerCell, String registerPass);
}